-- MySQL Script generated by MySQL Workbench
-- Mon Mar  2 14:54:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`comunitats_autonomes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comunitats_autonomes` (
  `comunitat_aut_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `codi_ine` CHAR(2) NOT NULL,
  PRIMARY KEY (`comunitat_aut_id`),
  UNIQUE INDEX `uk_com_aut_codi_ine` (`codi_ine` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`provincies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`provincies` (
  `provincia_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `codi_ine` CHAR(2) NOT NULL,
  `comunitat_aut_id` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`provincia_id`),
  UNIQUE INDEX `uk_provincies_codi_ine` (`codi_ine` ASC) VISIBLE,
  INDEX `idx_fk_provincies_comunitats_autonomes` (`comunitat_aut_id` ASC) VISIBLE,
  CONSTRAINT `fk_provincies_comunitats_autonomes`
    FOREIGN KEY (`comunitat_aut_id`)
    REFERENCES `mydb`.`comunitats_autonomes` (`comunitat_aut_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`municipis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`municipis` (
  `municipi_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NULL,
  `codi_ine` CHAR(3) NOT NULL,
  `provincia_id` TINYINT UNSIGNED NOT NULL,
  `districte` CHAR(2) NULL COMMENT 'Número de districte municipal , sinó el seu valor serà 99 si és el total municipal',
  PRIMARY KEY (`municipi_id`),
  UNIQUE INDEX `uk_municipis_codi_ine` (`codi_ine` ASC) VISIBLE,
  INDEX `idx_fk_municipis_provincies1` (`provincia_id` ASC) VISIBLE,
  CONSTRAINT `fk_municipis_provincies`
    FOREIGN KEY (`provincia_id`)
    REFERENCES `mydb`.`provincies` (`provincia_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`eleccions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`eleccions` (
  `eleccio_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `any` YEAR NOT NULL COMMENT 'any el qual s\'han celebrat les eleccions',
  `mes` TINYINT UNSIGNED NOT NULL COMMENT 'El mes que s\'han celebrat les eleccions',
  `data` DATE NOT NULL COMMENT 'Data (dia mes i any) de quan s\'han celebrat les eleccions',
  PRIMARY KEY (`eleccio_id`),
  UNIQUE INDEX `uk_eleccions_any_mes` USING BTREE (`any`, `mes`) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`eleccions_municipis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`eleccions_municipis` (
  `eleccio_municipi_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `eleccio_id` TINYINT UNSIGNED NOT NULL,
  `municipi_id` SMALLINT UNSIGNED NOT NULL,
  `num_meses` SMALLINT UNSIGNED NULL,
  `poblacio` INT UNSIGNED NULL,
  `cens` INT UNSIGNED NULL,
  `vots_emesos` INT UNSIGNED NULL COMMENT 'Número total de vots realitzats en el municipi',
  `vots_valids` INT UNSIGNED NULL COMMENT 'Número de vots es que tindran en compte: vots a candidatures + vots nuls',
  `vots_candidatures` INT UNSIGNED NULL,
  `vots_blanc` INT UNSIGNED NULL,
  `vots_nuls` INT UNSIGNED NULL,
  INDEX `idx_fk_eleccions_municipis_eleccions` (`eleccio_id` ASC) VISIBLE,
  INDEX `fk_eleccions_municipis_municipis` (`municipi_id` ASC) VISIBLE,
  PRIMARY KEY (`eleccio_municipi_id`),
  UNIQUE INDEX `uk_eleccions_municipis` (`eleccio_id` ASC, `municipi_id` ASC) VISIBLE,
  CONSTRAINT `fk_eleccions_municipis_municipis`
    FOREIGN KEY (`municipi_id`)
    REFERENCES `mydb`.`municipis` (`municipi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eleccions_municipis_eleccions`
    FOREIGN KEY (`eleccio_id`)
    REFERENCES `mydb`.`eleccions` (`eleccio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`partits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`partits` (
  `partit_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom_llarg` VARCHAR(100) NULL,
  `nom_curt` VARCHAR(50) NULL,
  PRIMARY KEY (`partit_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`candidatures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`candidatures` (
  `candidatura_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `eleccio_id` TINYINT UNSIGNED NOT NULL,
  `partit_id` SMALLINT UNSIGNED NOT NULL,
  `nom_curt` VARCHAR(50) NULL,
  `nom_llarg` VARCHAR(100) NULL,
  `codi_acumulacio_provincia` CHAR(6) NULL COMMENT 'Codi de la candidatura d\'acumulació a nivell provincial.',
  `codi_acumulacio_ca` CHAR(6) NULL COMMENT 'Codi de la candidatura d\'acumulació a nivell de comunitat autònoma',
  PRIMARY KEY (`candidatura_id`),
  INDEX `idx_fk_eleccions_partits_partits` (`partit_id` ASC) VISIBLE,
  INDEX `idx_fk_eleccions_partits_eleccions` (`eleccio_id` ASC) VISIBLE,
  UNIQUE INDEX `uk_eleccions_partits` (`eleccio_id` ASC, `partit_id` ASC) VISIBLE,
  CONSTRAINT `fk_eleccions_partits_eleccions`
    FOREIGN KEY (`eleccio_id`)
    REFERENCES `mydb`.`eleccions` (`eleccio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eleccions_partits_partits`
    FOREIGN KEY (`partit_id`)
    REFERENCES `mydb`.`partits` (`partit_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`persones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`persones` (
  `persona_id` INT UNSIGNED NOT NULL,
  `nom` VARCHAR(30) NULL,
  `cog1` VARCHAR(30) NULL,
  `cog2` VARCHAR(30) NULL,
  `sexe` ENUM('M', 'F') NULL COMMENT 'M=Masculí, F=Femení',
  `data_naixement` DATE NULL,
  `dni` CHAR(10) NOT NULL,
  PRIMARY KEY (`persona_id`),
  UNIQUE INDEX `uk_candidats_dni` (`dni` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`candidats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`candidats` (
  `candidat_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `num_ordre` TINYINT NULL COMMENT 'Num ordre del candidatdins la llista del partit dins de la circumpscripció que es presenta.',
  `tipus` ENUM('T', 'S') NULL COMMENT 'T=Titular, S=Suplent',
  `provincia_id` TINYINT UNSIGNED NOT NULL,
  `persona_id` INT UNSIGNED NOT NULL,
  `candidatura_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`candidat_id`),
  INDEX `fk_candidats_provincies1_idx` (`provincia_id` ASC) VISIBLE,
  INDEX `fk_candidats_persones1_idx` (`persona_id` ASC) VISIBLE,
  INDEX `fk_candidats_candidatures1_idx` (`candidatura_id` ASC) VISIBLE,
  CONSTRAINT `fk_candidats_provincies1`
    FOREIGN KEY (`provincia_id`)
    REFERENCES `mydb`.`provincies` (`provincia_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidats_persones1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `mydb`.`persones` (`persona_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidats_candidatures1`
    FOREIGN KEY (`candidatura_id`)
    REFERENCES `mydb`.`candidatures` (`candidatura_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
